// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABzXFwNt5jr78fFcyLyaO4c5gKmZeLbDo',
    appId: '1:1083546212926:web:4a08e9f6c174fe6b7d8f6f',
    messagingSenderId: '1083546212926',
    projectId: 'emoshield-f9dfc',
    authDomain: 'emoshield-f9dfc.firebaseapp.com',
    storageBucket: 'emoshield-f9dfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmfQ_Dbdt6zpbW-ezWVKI0A4_ZyfAfGQ',
    appId: '1:1083546212926:android:351b491b01e725857d8f6f',
    messagingSenderId: '1083546212926',
    projectId: 'emoshield-f9dfc',
    storageBucket: 'emoshield-f9dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBttLiE6xIOWQgttkSMtYq5XnNX09s-Ksk',
    appId: '1:1083546212926:ios:4fb4a85dff8d6c757d8f6f',
    messagingSenderId: '1083546212926',
    projectId: 'emoshield-f9dfc',
    storageBucket: 'emoshield-f9dfc.firebasestorage.app',
    iosBundleId: 'com.example.emoshieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBttLiE6xIOWQgttkSMtYq5XnNX09s-Ksk',
    appId: '1:1083546212926:ios:4fb4a85dff8d6c757d8f6f',
    messagingSenderId: '1083546212926',
    projectId: 'emoshield-f9dfc',
    storageBucket: 'emoshield-f9dfc.firebasestorage.app',
    iosBundleId: 'com.example.emoshieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABzXFwNt5jr78fFcyLyaO4c5gKmZeLbDo',
    appId: '1:1083546212926:web:826b677cd64a1db97d8f6f',
    messagingSenderId: '1083546212926',
    projectId: 'emoshield-f9dfc',
    authDomain: 'emoshield-f9dfc.firebaseapp.com',
    storageBucket: 'emoshield-f9dfc.firebasestorage.app',
  );
}
